version: '3.8'

# Development override for docker-compose.yml
services:
  app:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_SHOW_SQL: true
    volumes:
      # Mount source code for hot reload (if using Spring Boot DevTools)
      - ./src:/app/src:ro
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port

  postgres:
    environment:
      POSTGRES_DB: ecommercespringboot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
